import { useState } from "react";

function App() {
  const [code, setCode] = useState("");
  const [style, setStyle] = useState("expert");
  const [tests, setTests] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  const [results, setResults] = useState(null);
  const [running, setRunning] = useState(false);
  const [activeTab, setActiveTab] = useState("tests");

  const generateTests = async () => {
    if (!code.trim()) {
      setError("Please paste your Python code first!");
      return;
    }
    setLoading(true);
    setError("");
    setTests("");
    setResults(null);
    try {
      const response = await fetch(
        "http://localhost:5000/generate",
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ code, style }),
        }
      );
      const data = await response.json();
      if (data.success) {
        setTests(data.tests);
        setActiveTab("tests");
      } else {
        setError(data.error || "Something went wrong!");
      }
    } catch (err) {
      setError("Cannot connect to server!");
    }
    setLoading(false);
  };

  const runTests = async () => {
    if (!tests) return;
    setRunning(true);
    try {
      const response = await fetch(
        "http://localhost:5000/run-tests",
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ tests, style }),
        }
      );
      const data = await response.json();
      if (data.success) {
        setResults(data.results);
        setActiveTab("results");
      }
    } catch (err) {
      setError("Cannot connect to server!");
    }
    setRunning(false);
  };

  const copyTests = () => {
    navigator.clipboard.writeText(tests);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadTests = () => {
    const blob = new Blob([tests], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `test_${style}_generated.py`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const countTests = (testCode) => {
    const matches = testCode.match(/def test_/g);
    return matches ? matches.length : 0;
  };

  const clearAll = () => {
    setCode("");
    setTests("");
    setResults(null);
    setError("");
  };

  return (
    <div style={s.page}>

     <nav style={s.nav}>
        <div style={s.navLeft}>
          <span style={s.navLogo}>TestGen AI</span>
          <span style={s.navBadge}>Beta</span>
        </div>
        <div style={s.navRight}>
          <a href="https://github.com/sarathbabuvazhottu-png/ai-test-generator" target="_blank" rel="noreferrer" style={s.navLink}>GitHub</a>
          <span style={s.navPowered}>Powered by Claude AI</span>
        </div>
      </nav>

      {/* Hero Section */}
      <div style={s.hero}>
        <div style={s.heroInner}>
          <div style={s.heroBadge}>
            AI Powered Testing Tool
          </div>
          <h1 style={s.heroTitle}>
            Generate Python Tests
            <span style={s.heroAccent}> Instantly</span>
          </h1>
          <p style={s.heroSub}>
            Paste your Python code and get comprehensive
            pytest test cases generated by Claude AI
            in seconds. No more manual test writing!
          </p>
          <div style={s.statsRow}>
            <div style={s.stat}>
              <span style={s.statNum}>151+</span>
              <span style={s.statLabel}>
                Tests Generated
              </span>
            </div>
            <div style={s.statLine}/>
            <div style={s.stat}>
              <span style={s.statNum}>100%</span>
              <span style={s.statLabel}>Pass Rate</span>
            </div>
            <div style={s.statLine}/>
            <div style={s.stat}>
              <span style={s.statNum}>3</span>
              <span style={s.statLabel}>
                Prompt Styles
              </span>
            </div>
            <div style={s.statLine}/>
            <div style={s.stat}>
              <span style={s.statNum}>100%</span>
              <span style={s.statLabel}>Coverage</span>
            </div>
          </div>
        </div>
      </div>

      {/* Tool Area */}
      <div style={s.toolArea}>

        {/* Left Panel */}
        <div style={s.panel}>
          <div style={s.panelTop}>
            <span style={s.panelTitle}>
              Your Python Code
            </span>
            <button style={s.clearBtn} onClick={clearAll}>
              Clear
            </button>
          </div>

          <div style={s.editorBox}>
            <div style={s.editorBar}>
              <div style={s.dots}>
                <span style={{
                  ...s.dot,
                  background: "#ff5f57"
                }}/>
                <span style={{
                  ...s.dot,
                  background: "#febc2e"
                }}/>
                <span style={{
                  ...s.dot,
                  background: "#28c840"
                }}/>
              </div>
              <span style={s.editorLang}>python</span>
            </div>
            <textarea
              style={s.editor}
              placeholder={
                "# Paste your Python code here\n\n" +
                "def add_numbers(a, b):\n" +
                "    return a + b\n\n" +
                "def divide_numbers(a, b):\n" +
                "    if b == 0:\n" +
                "        raise ValueError('Cannot divide by zero')\n" +
                "    return a / b"
              }
              value={code}
              onChange={(e) => setCode(e.target.value)}
              spellCheck={false}
            />
          </div>

          <div style={s.styleBox}>
            <span style={s.styleTitle}>Prompt Style</span>
            <div style={s.styleBtns}>
              {[
                {
                  id: "basic",
                  label: "Basic",
                  desc: "Simple and fast"
                },
                {
                  id: "detailed",
                  label: "Detailed",
                  desc: "Edge cases included"
                },
                {
                  id: "expert",
                  label: "Expert",
                  desc: "All possible tests"
                },
              ].map((item) => (
                <button
                  key={item.id}
                  style={{
                    ...s.styleBtn,
                    ...(style === item.id
                      ? s.styleBtnOn
                      : {}),
                  }}
                  onClick={() => setStyle(item.id)}
                >
                  <span style={s.styleBtnLabel}>
                    {item.label}
                  </span>
                  <span style={s.styleBtnDesc}>
                    {item.desc}
                  </span>
                </button>
              ))}
            </div>
          </div>

          <button
            style={{
              ...s.genBtn,
              ...(loading ? s.genBtnOff : {}),
            }}
            onClick={generateTests}
            disabled={loading}
          >
            {loading
              ? "Generating with Claude AI..."
              : "Generate Tests"}
          </button>

          {error && (
            <div style={s.errBox}>
              {error}
            </div>
          )}
        </div>

        {/* Right Panel */}
        <div style={s.panel}>
          <div style={s.tabs}>
            <button
              style={{
                ...s.tab,
                ...(activeTab === "tests"
                  ? s.tabOn
                  : {}),
              }}
              onClick={() => setActiveTab("tests")}
            >
              Generated Tests
              {tests && (
                <span style={s.badge}>
                  {countTests(tests)}
                </span>
              )}
            </button>
            <button
              style={{
                ...s.tab,
                ...(activeTab === "results"
                  ? s.tabOn
                  : {}),
              }}
              onClick={() => setActiveTab("results")}
            >
              Results
              {results && (
                <span style={{
                  ...s.badge,
                  background: results.failed > 0
                    ? "#ef4444"
                    : "#22c55e"
                }}>
                  {results.pass_rate}
                </span>
              )}
            </button>
          </div>

          {activeTab === "tests" && (
            <div style={s.outPanel}>
              {tests ? (
                <>
                  <div style={s.actBar}>
                    <button
                      style={{
                        ...s.runBtn,
                        ...(running ? s.runBtnOff : {}),
                      }}
                      onClick={runTests}
                      disabled={running}
                    >
                      {running
                        ? "Running..."
                        : "Run Tests"}
                    </button>
                    <button
                      style={s.actBtn}
                      onClick={copyTests}
                    >
                      {copied ? "Copied!" : "Copy"}
                    </button>
                    <button
                      style={s.actBtn}
                      onClick={downloadTests}
                    >
                      Download
                    </button>
                  </div>
                  <pre style={s.codeOut}>
                    {tests}
                  </pre>
                </>
              ) : (
                <div style={s.empty}>
                  <div style={s.emptyIcon}>
                    🤖
                  </div>
                  <p style={s.emptyTitle}>
                    Ready to generate tests!
                  </p>
                  <p style={s.emptySub}>
                    Paste your Python code on the left
                    and click Generate Tests
                  </p>
                  <div style={s.steps}>
                    {[
                      "Paste your Python code",
                      "Select prompt style",
                      "Click Generate Tests!",
                    ].map((step, i) => (
                      <div key={i} style={s.step}>
                        <span style={s.stepNum}>
                          {i + 1}
                        </span>
                        {step}
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {activeTab === "results" && (
            <div style={s.outPanel}>
              {results ? (
                <div>
                  <div style={s.circleBox}>
                    <div style={{
                      ...s.circle,
                      borderColor:
                        results.pass_rate === "100.0%"
                          ? "#22c55e"
                          : "#f59e0b"
                    }}>
                      <span style={s.circleNum}>
                        {results.pass_rate}
                      </span>
                      <span style={s.circleLabel}>
                        Pass Rate
                      </span>
                    </div>
                  </div>

                  <div style={s.grid3}>
                    <div style={s.card}>
                      <span style={s.cardNum}>
                        {results.total}
                      </span>
                      <span style={s.cardLabel}>
                        Total
                      </span>
                    </div>
                    <div style={{
                      ...s.card,
                      borderTop: "3px solid #22c55e"
                    }}>
                      <span style={{
                        ...s.cardNum,
                        color: "#22c55e"
                      }}>
                        {results.passed}
                      </span>
                      <span style={s.cardLabel}>
                        Passed
                      </span>
                    </div>
                    <div style={{
                      ...s.card,
                      borderTop: results.failed > 0
                        ? "3px solid #ef4444"
                        : "3px solid #22c55e"
                    }}>
                      <span style={{
                        ...s.cardNum,
                        color: results.failed > 0
                          ? "#ef4444"
                          : "#22c55e"
                      }}>
                        {results.failed}
                      </span>
                      <span style={s.cardLabel}>
                        Failed
                      </span>
                    </div>
                  </div>

                  <div style={s.progBox}>
                    <div style={s.progLabel}>
                      <span>Pass Rate</span>
                      <span>{results.pass_rate}</span>
                    </div>
                    <div style={s.progBg}>
                      <div style={{
                        ...s.progFill,
                        width: results.pass_rate,
                        background:
                          results.pass_rate === "100.0%"
                            ? "#22c55e"
                            : "#f59e0b"
                      }}/>
                    </div>
                  </div>

                  <div style={s.detailBox}>
                    {[
                      {
                        label: "AI Model",
                        value: "Claude Sonnet"
                      },
                      {
                        label: "Prompt Style",
                        value: style
                      },
                      {
                        label: "Tests Generated",
                        value: countTests(tests)
                      },
                    ].map((row, i) => (
                      <div key={i} style={s.detailRow}>
                        <span style={s.detailLabel}>
                          {row.label}
                        </span>
                        <span style={s.detailVal}>
                          {row.value}
                        </span>
                      </div>
                    ))}
                  </div>

                  {results.output && (
                    <div style={s.termBox}>
                      <div style={s.termHeader}>
                        Terminal Output
                      </div>
                      <pre style={s.termCode}>
                        {results.output}
                      </pre>
                    </div>
                  )}
                </div>
              ) : (
                <div style={s.empty}>
                  <div style={s.emptyIcon}>📊</div>
                  <p style={s.emptyTitle}>
                    No results yet!
                  </p>
                  <p style={s.emptySub}>
                    Generate tests first then
                    click Run Tests!
                  </p>
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      {/* Footer */}
      <footer style={s.footer}>
        <span style={s.footerLeft}>
          TestGen AI — Built For Developers, Python,
          React, Flask
        </span>
        <div style={s.footerRight}>
          {["Software Testing", "AI Powered",
            "Open Source"].map((tag) => (
            <span key={tag} style={s.tag}>{tag}</span>
          ))}
        </div>
      </footer>
    </div>
  );
}

const s = {
  page: {
    minHeight: "100vh",
    background: "#0f1117",
    color: "#e2e8f0",
    fontFamily: "'Segoe UI', Arial, sans-serif",
  },
  nav: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0 32px",
    height: "60px",
    background: "#161b27",
    borderBottom: "1px solid #2d3748",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  navLeft: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  navLogo: {
    fontSize: "1.1rem",
    fontWeight: "700",
    color: "#fff",
  },
  navBadge: {
    background: "#3b82f6",
    color: "white",
    fontSize: "0.7rem",
    padding: "2px 8px",
    borderRadius: "20px",
    fontWeight: "600",
  },
  navRight: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  navLink: {
    color: "#94a3b8",
    textDecoration: "none",
    fontSize: "0.9rem",
  },
  navPowered: {
    color: "#64748b",
    fontSize: "0.85rem",
  },
  hero: {
    background: "#161b27",
    borderBottom: "1px solid #2d3748",
    padding: "50px 32px 40px",
  },
  heroInner: {
    maxWidth: "900px",
    margin: "0 auto",
  },
  heroBadge: {
    display: "inline-block",
    background: "rgba(59,130,246,0.15)",
    color: "#60a5fa",
    border: "1px solid rgba(59,130,246,0.3)",
    padding: "6px 16px",
    borderRadius: "20px",
    fontSize: "0.85rem",
    fontWeight: "600",
    marginBottom: "20px",
  },
  heroTitle: {
    fontSize: "2.8rem",
    fontWeight: "800",
    color: "#fff",
    margin: "0 0 16px 0",
    lineHeight: "1.2",
  },
  heroAccent: {
    color: "#60a5fa",
  },
  heroSub: {
    fontSize: "1.1rem",
    color: "#94a3b8",
    margin: "0 0 32px 0",
    lineHeight: "1.7",
    maxWidth: "600px",
  },
  statsRow: {
    display: "flex",
    alignItems: "center",
    gap: "24px",
    flexWrap: "wrap",
  },
  stat: {
    display: "flex",
    flexDirection: "column",
  },
  statNum: {
    fontSize: "1.8rem",
    fontWeight: "800",
    color: "#60a5fa",
    lineHeight: "1",
  },
  statLabel: {
    fontSize: "0.8rem",
    color: "#64748b",
    marginTop: "4px",
  },
  statLine: {
    width: "1px",
    height: "40px",
    background: "#2d3748",
  },
  toolArea: {
    display: "flex",
    minHeight: "calc(100vh - 280px)",
  },
  panel: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    borderRight: "1px solid #2d3748",
    minWidth: 0,
  },
  panelTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px 20px",
    borderBottom: "1px solid #2d3748",
    background: "#161b27",
  },
  panelTitle: {
    fontSize: "0.95rem",
    fontWeight: "600",
    color: "#e2e8f0",
  },
  clearBtn: {
    background: "transparent",
    border: "1px solid #374151",
    color: "#9ca3af",
    padding: "4px 12px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "0.8rem",
  },
  editorBox: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    margin: "16px",
    border: "1px solid #2d3748",
    borderRadius: "8px",
    overflow: "hidden",
  },
  editorBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 12px",
    background: "#1e2535",
    borderBottom: "1px solid #2d3748",
  },
  dots: {
    display: "flex",
    gap: "6px",
  },
  dot: {
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    display: "inline-block",
  },
  editorLang: {
    color: "#64748b",
    fontSize: "0.8rem",
  },
  editor: {
    flex: 1,
    background: "#1a1f2e",
    color: "#e2e8f0",
    border: "none",
    padding: "16px",
    fontFamily: "monospace",
    fontSize: "0.9rem",
    resize: "none",
    outline: "none",
    minHeight: "300px",
    lineHeight: "1.6",
  },
  styleBox: {
    padding: "16px",
    borderTop: "1px solid #2d3748",
  },
  styleTitle: {
    fontSize: "0.8rem",
    color: "#64748b",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    display: "block",
    marginBottom: "10px",
  },
  styleBtns: {
    display: "flex",
    gap: "8px",
  },
  styleBtn: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "10px 8px",
    borderRadius: "8px",
    border: "1px solid #2d3748",
    background: "#1a1f2e",
    cursor: "pointer",
    gap: "2px",
  },
  styleBtnOn: {
    border: "1px solid #3b82f6",
    background: "rgba(59,130,246,0.1)",
  },
  styleBtnLabel: {
    fontSize: "0.85rem",
    fontWeight: "600",
    color: "#e2e8f0",
  },
  styleBtnDesc: {
    fontSize: "0.7rem",
    color: "#64748b",
  },
  genBtn: {
    margin: "0 16px 16px",
    padding: "14px",
    borderRadius: "8px",
    border: "none",
    background: "linear-gradient(135deg, #3b82f6, #1d4ed8)",
    color: "white",
    fontSize: "1rem",
    fontWeight: "700",
    cursor: "pointer",
  },
  genBtnOff: {
    opacity: 0.7,
    cursor: "not-allowed",
  },
  errBox: {
    margin: "0 16px 16px",
    padding: "12px",
    borderRadius: "8px",
    background: "rgba(239,68,68,0.1)",
    border: "1px solid rgba(239,68,68,0.3)",
    color: "#f87171",
    fontSize: "0.9rem",
  },
  tabs: {
    display: "flex",
    borderBottom: "1px solid #2d3748",
    background: "#161b27",
  },
  tab: {
    flex: 1,
    padding: "14px 16px",
    background: "transparent",
    border: "none",
    color: "#64748b",
    cursor: "pointer",
    fontSize: "0.9rem",
    fontWeight: "500",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    borderBottom: "2px solid transparent",
  },
  tabOn: {
    color: "#60a5fa",
    borderBottom: "2px solid #3b82f6",
    background: "rgba(59,130,246,0.05)",
  },
  badge: {
    background: "#3b82f6",
    color: "white",
    fontSize: "0.75rem",
    padding: "2px 8px",
    borderRadius: "20px",
    fontWeight: "700",
  },
  outPanel: {
    flex: 1,
    overflow: "auto",
    padding: "16px",
  },
  actBar: {
    display: "flex",
    gap: "8px",
    marginBottom: "12px",
  },
  runBtn: {
    padding: "8px 16px",
    borderRadius: "6px",
    border: "none",
    background: "#22c55e",
    color: "white",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "0.9rem",
  },
  runBtnOff: {
    opacity: 0.7,
    cursor: "not-allowed",
  },
  actBtn: {
    padding: "8px 14px",
    borderRadius: "6px",
    border: "1px solid #2d3748",
    background: "#1a1f2e",
    color: "#94a3b8",
    cursor: "pointer",
    fontSize: "0.85rem",
  },
  codeOut: {
    background: "#0d1117",
    color: "#e2e8f0",
    padding: "16px",
    borderRadius: "8px",
    fontSize: "0.82rem",
    overflow: "auto",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    border: "1px solid #2d3748",
    lineHeight: "1.6",
    fontFamily: "monospace",
  },
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "60px 20px",
    textAlign: "center",
  },
  emptyIcon: {
    fontSize: "3rem",
    marginBottom: "16px",
  },
  emptyTitle: {
    fontSize: "1.1rem",
    fontWeight: "600",
    color: "#e2e8f0",
    margin: "0 0 8px 0",
  },
  emptySub: {
    color: "#64748b",
    fontSize: "0.9rem",
    margin: "0 0 24px 0",
    lineHeight: "1.6",
  },
  steps: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    width: "100%",
    maxWidth: "280px",
  },
  step: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    color: "#94a3b8",
    fontSize: "0.9rem",
    textAlign: "left",
  },
  stepNum: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    background: "rgba(59,130,246,0.15)",
    border: "1px solid rgba(59,130,246,0.3)",
    color: "#60a5fa",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.8rem",
    fontWeight: "700",
    flexShrink: 0,
  },
  circleBox: {
    display: "flex",
    justifyContent: "center",
    padding: "24px 0",
  },
  circle: {
    width: "140px",
    height: "140px",
    borderRadius: "50%",
    border: "6px solid #22c55e",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  circleNum: {
    fontSize: "1.8rem",
    fontWeight: "800",
    color: "#fff",
  },
  circleLabel: {
    fontSize: "0.75rem",
    color: "#64748b",
  },
  grid3: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr",
    gap: "12px",
    marginBottom: "20px",
  },
  card: {
    background: "#1a1f2e",
    border: "1px solid #2d3748",
    borderTop: "3px solid #3b82f6",
    borderRadius: "8px",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "4px",
  },
  cardNum: {
    fontSize: "2rem",
    fontWeight: "800",
    color: "#fff",
  },
  cardLabel: {
    fontSize: "0.8rem",
    color: "#64748b",
  },
  progBox: {
    marginBottom: "20px",
  },
  progLabel: {
    display: "flex",
    justifyContent: "space-between",
    color: "#94a3b8",
    fontSize: "0.85rem",
    marginBottom: "8px",
  },
  progBg: {
    background: "#1a1f2e",
    borderRadius: "10px",
    height: "10px",
    overflow: "hidden",
  },
  progFill: {
    height: "100%",
    borderRadius: "10px",
  },
  detailBox: {
    background: "#1a1f2e",
    borderRadius: "8px",
    border: "1px solid #2d3748",
    overflow: "hidden",
    marginBottom: "16px",
  },
  detailRow: {
    display: "flex",
    justifyContent: "space-between",
    padding: "12px 16px",
    borderBottom: "1px solid #2d3748",
  },
  detailLabel: {
    color: "#64748b",
    fontSize: "0.9rem",
  },
  detailVal: {
    color: "#e2e8f0",
    fontWeight: "600",
    fontSize: "0.9rem",
  },
  termBox: {
    border: "1px solid #2d3748",
    borderRadius: "8px",
    overflow: "hidden",
  },
  termHeader: {
    background: "#1e2535",
    padding: "8px 16px",
    fontSize: "0.8rem",
    color: "#64748b",
    borderBottom: "1px solid #2d3748",
  },
  termCode: {
    background: "#0d1117",
    color: "#e2e8f0",
    padding: "16px",
    fontSize: "0.78rem",
    overflow: "auto",
    maxHeight: "200px",
    whiteSpace: "pre-wrap",
    margin: 0,
    fontFamily: "monospace",
  },
  footer: {
    borderTop: "1px solid #2d3748",
    background: "#161b27",
    padding: "20px 32px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "16px",
  },
  footerLeft: {
    color: "#64748b",
    fontSize: "0.85rem",
  },
  footerRight: {
    display: "flex",
    gap: "8px",
  },
  tag: {
    background: "#1a1f2e",
    border: "1px solid #2d3748",
    color: "#64748b",
    padding: "4px 12px",
    borderRadius: "20px",
    fontSize: "0.8rem",
  },
};

export default App;